apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: marketplace
labels:
  - pairs:
      env: production
    includeSelectors: false
resources:
  - ../../base
configMapGenerator:
  - name: prod-config
    literals:
      - APP_ENV=production
